puts "Destroying database"

User.destroy_all
Experience.destroy_all
Booking.destroy_all

puts "Seeding users...👥"

u1= User.create(username:"ohheycerimay", password_digest:"1234", image_url:"https://i0.wp.com/bkreader.com/wp-content/uploads/2014/04/g-train.jpg?fit=500%2C380&ssl=1")
u2= User.create(username:"luimatthew", password_digest:"5678", image_url:"https://media.istockphoto.com/id/1309040743/photo/travel-planning-background.jpg?b=1&s=170667a&w=0&k=20&c=oYsf4vJ1lCmKJAwq1DAIte1KH56qCmiyNDvoysDHUhQ=")
u3= User.create(username:"paigetetz", password_digest:"9876", image_url:"http://cdn.akc.org/content/article-body-image/siberian_husky_cute_puppies.jpg")

puts "Users seeded!"

puts "Seeding experiences..."

e1= Experience.create(name: "Private Full-Day Suzhou Excursion", location:"Shanghai, China", description:"Take a journey to the waterside city of Suzhou close to the eastern shore of Lake Taihu where the Grand Canal joins the Yangtze River. Experience unforgettable views of stone architecture, wander through labyrinth-like gardens, and learn why the town is an important center for China's silk industry.
Get picked up from your hotel and reach the port of Suzhou—a popular site because of its fascinating historic architecture in the form of bridges and pagodas set on the water. Hop out of the vehicle and snap some photos of the snaking canals, pools, and island, connected by postcard-perfect zigzag bridges. Travel to Tiger Hill, named such because of its likeness to the shape of a crouching tiger. Enter through decorated gates and take a stroll around the hill, discovering impressive structures, including seven-story Yunyan Pagoda.
Next, see the natural wonder of Master of Nets Garden. The UNESCO World Heritage Site is skillfully designed to mix features of art, nature, and architecture to create a truly enveloping experience. After this, head to the Silk Factory, where you begin to understand the importance of silk in Suzhou's history and why the city continues to be a prominent producer of the luxurious fabric today. Finish your full-day trip at the Leoh Ming Pei-designed Suzhou Museum.
", price: 692, image_url:"https://mediaim.expedia.com/localexpert/303556/ce95c448-e58c-4d5b-9f98-cba73cf1c150.jpg?impolicy=resizecrop&rw=1005&rh=565 ", includes:"", likes:1204)
e2= Experience.create(name: "Paris Versailles Tour", location:"Paris, France", description:"Travel from Paris on this half-day trip to Versailles. Save time with skip-the-line tickets, a convenient return transfer, and an engaging tour of Versailles Palace and its historic rooms and chambers.
Start by meeting at a central point in Paris and transfer by bus to Versailles. Upon arrival, access the palace through a separate entrance. Then, discover the opulence, beauty, and history of the palace on an interactive guided tour.
During the 90-minute tour, see the State Apartments, the King's Bedroom, and the emblematic Hall of Mirrors. Learn about the main figures of the French monarchy, from King Louis XIV to Marie Antoinette. Hear about the many fascinating historical events that took place in the palace's rooms.
After your tour of the palace, take some free time to stroll around the beautiful French Gardens. After some time exploring the gardens by yourself, hop back on the bus for your journey back to central Paris.
", price:106, image_url:"https://mediaim.expedia.com/localexpert/44622301/d53743b3-4b1f-4c44-96f8-a745c7919f07.jpg?impolicy=resizecrop&rw=1005&rh=565 ", includes:"", likes:451)
e3= Experience.create(name: "Bora Bora Luxury Private Treasure Hunt ", location:"Bora-Bora, France", description:"The perfect kids day out on the lagoon on a private luxury boat!
A truly out-of-the-ordinary cruise, designed for kids to discover the lagoon of Bora Bora in an engaging way! It includes 3 to 4 stops (depending on the kids age) where kids collect clues on how to reach the Treasure. Encountered along the journey: Manta rays, tropical fish in the coral garden, eagle rays, and much more. Each boat can carry up to 8 passengers so you can add people to your party if desired.
Our captain will supervise and guide the kids at each stop. A fun informative themed tour that keeps parents and little ones engaged!", price:475, image_url:"https://www.lindsaysilberman.com/wp-content/uploads/2021/10/four-seasons-bora-bora-review-09-1140x760.jpg", includes:"", likes:765)
e4= Experience.create(name: "Montserrat Tour with Skip-the-Line to The Black Madonna
", location:"Monserrat, Virgin Islands", description:"Leave our office in central Barcelona on an air-conditioned coach towards Montserrat. After a 1h drive on the highway, board the cog-wheel train up the mountain and enjoy the amazing views over the area. Admire the Mountain’s peculiar morphology, which comes from the Catalan words Mont (mountain) and Serrat (serrated). World-famous for its rocky geography, Montserrat beautiful scenery was declared National Park in 1987 to protect its natural and cultural wealth.
Follow your local guide through the site and learn about the history and architectural style of the Monastery. A community of 80 monks currently lives and follow the rule of Saint Benedict in Montserrat. Fall in love with the Gothic and Renaissance details of the basilica and sanctuary. Learn about the legend of the miraculous apparition of the Madonna and Child in the cave of Santa Cova.To this day their wood carving is kept in the Church of the monastery, which you will be able to visit. The figure is popularly known as La Moreneta(The Black Madonna) as a result of a varnish reaction.
Besides the main area, there are a great number of small churches and trails you can follow. You will be given free time to taste the finest liquors, shop for locally produced treats or visit the audio visual exhibition once our guided tour finishes.
Upgrade your experience with the option that includes the access to the basilica when the Boys’ Choir is singing. This is one of the oldest Boys’ Choir in Europe, and they sing every day form Monday to Friday at 13:00h. This option also includes the skip the line to the Black Madonna, “La Moreneta”.", price:60, image_url:"https://mediaim.expedia.com/localexpert/167451/ac2a22c6-085e-48ac-9f2f-ef7d369361fb.jpg?impolicy=resizecrop&rw=1005&rh=565 ", includes:"", likes:713)
e5= Experience.create(name: "Eze & Saint-Paul de Vence Private Half-Day Tour ", location:"Monaco", description:"With this half-day private tour, you will discover the medieval age of the perch village of Eze & the Modern Art of the medieval village of St. Paul de Vence.
Discover the ​village of Eze​ with its medieval history, its exotic gardens, and its incredible panoramic view! Discover the statue of Emperor Augustus, also called the Trophy of the Alps of the village of La Turbie and the magnificent view from the heights of the Great Corniche. Finally, you will be entitled to the most beautiful view of the Côte d'Azur from the Dogs Head a place known only to the premises in which we keep the secret.
Discover the village of St. Paul de Vence, the city of art. A source of inspiration for some of the greatest artists such as Picasso, Matisse, and Chagall. The artists stayed most of the time at the Hotel Colombe dor, very famous today.This tour is limited to a single booking of up to 4 people as it is a private tour with a private guide.
", price: 540, image_url:"https://live.staticflickr.com/6046/6305292203_1070dbaff0_b.jpg ", includes:"", likes:111)
e6= Experience.create(name: "Santorini Wine Tasting and Vineyard Tour", location:"Santorini, Greece", description:"Discover Santorini through its wineries during a half-day, small-group island tour. Visit three popular vineyards and taste up to 12 different varietals made from grapes such as Assyrtiko. Learn about Santorini’s famous volcanic vineyards and local wine production methods. Customize the tour to also include a wine tasting at sunset with traditional snacks.", price:152, image_url:"https://a.cdn-hotels.com/gdcs/production18/d1838/041ae6b1-0a88-4c22-a648-53a22dd4a006.jpg ", includes:"", likes:605)
e7= Experience.create(name: "Aurora Hunt Tour with Citizen Science from Tromso", location:"Tromso, Norway", description:"The Northern Lights are notoriously hard to predict, even in Tromso. So it makes sense to increase your chances of a sighting by joining a guided excursion, especially if you’re only in Tromso briefly. This tour delivers—a guide chooses a prime viewpoint according to the day’s weather and you'll enjoy soup beside a firelit camp as you watch. A drop-off back at your hotel afterward is included.", price:190, image_url:"https://www.travelandleisure.com/thmb/7vHDx6UqUNlqFeNkynyw92xwmmw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/lofoten-islands-norway-aurora-borealis-northern-lights-NORWAYLIGHTS1017-20d82f5331f342099cdb418e95809dad.jpg ", includes:"", likes:150)
e8= Experience.create(name: "Intimate Sailing Adventure in Miami's Biscayne Bay ", location:"Miami, Florida", description:"See the beauty of Biscayne Bay from a whole new perspective with this sailing adventure. No need to worry about crowds on the boat—this is a private tour with just the crew and your party. Ride along the coastline in an eco-friendly wind-powered sailing boat, and visit sandbars, mangroves, and islets along the way. If you're lucky—you may even spot dolphins or manatees—which are frequently spotted around the bay.", price:129, image_url:"https://images.unsplash.com/photo-1523496922380-91d5afba98a3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2532&q=80 ", includes:"", likes:413)
e9= Experience.create(name: "Private Helicopter over Manhattan, Brooklyn, & Staten Island", location:"New York City, United States", description:"Discover New York City’s must-see sites from above on this helicopter tour of Manhattan, Brooklyn and beyond. See dazzling skyscrapers and elegant bridges, sprawling Central Park, the Empire State Building, the Statue of Liberty and Ellis Island, and more. Multiple departures are available to suit your schedule and all fees and surcharges are included.", price:369, image_url:"https://i.ytimg.com/vi/q1CctfCfVu8/maxresdefault.jpg", includes:"", likes:516)
e10= Experience.create(name: "Sydney Harbor Cruise w/ High Tea",location:"Sydney, Australia", description:"Take in charming views of Sydney and its surroundings while enjoying a selection of savory and sweet treats and a glass of sparkling wine. Hop aboard the prestigious MV Sydney 2000 or John Cadman 2 for first-class service and a perfect combination of cruising and relaxation with spectacular views.
When you board the ship, meet the friendly staff and enjoy a glass of sparkling wine. Travel the harbor's shimmering waters in style aboard one of Sydney's most prestigious cruise ships. Stay in the comfortable lounge or go out on the deck to take in the marvelous views of Sydney Harbor from your super-cruiser.
Cruise along some of the most celebrated sights in Australia, such as the elegant Sydney Opera House and iconic Sydney Harbor Bridge. Enjoy a delicious variety of finger sandwiches, pastries and tartlets, scones and petit fours presented on tiered platters, and accompanied by a selection of premium teas.
Get one more glimpse of the spectacular Sydney Harbour and create memories that will last a lifetime before disembarking the cruise.
", price: 60, image_url:"https://s1.at.atcdn.net/wp-content/uploads/2005/09/Sydney-Harbour-Bridge-800x584.jpg ", includes:"", likes:616)
e11= Experience.create(name: "Platinum Safari Experience at Arabian Desert",location:"United Arab Emirates", description:"Want to visit the Dubai Desert Safari and be looked upon as a Royal; well Luxury Desert Safari Dubai is your best choice, as you will have an experience worth every minute and penny. Book our Royal Luxury Safari and experience the Luxury Safari Dubai in style as you will be picked up from and dropped back to your hotel in a luxurious Mercedes AMG G63. Upon reaching, enjoy the most thrilling ride and feel the adrenaline rush your veins as our expert driver takes you up and down the enormous sand dunes leaving you screaming out loud. After the thrilling ride, view as the sun sets behind the gigantic sand dunes and give an expansive glance over the vast desert. After sunset, you’ll be escorted to the most remarkable Sahara Experience located deep in the Desert Fortress, where you’ll be welcomed with warm dated and the traditional Arabian Coffee.", price:1500, image_url:"https://media.cntraveler.com/photos/59ea1279cae8da16e6cd4b0a/master/pass/Arabian-Adventures_Overnigth-Safari.jpg ", includes:"", likes:144)
e12= Experience.create(name: "Serengeti Breakfast and Hot Air Balloon",location:"Tanzania, Africa", description:"Explore the untouched parts of Serengeti as you casually drift away from the surface of the earth in the early hours of the morning, safe in the basket of a hot air balloon.
Join us for a luxurious UNFORGETTABLE balloon safari in Serengeti followed by a lavish Bush Breakfast.
With a permanent base in Seronera, the heart of the Serengeti, and seasonal bases in Ndutu, Kogatende, and Kirawira, we follow the migration all year round.
", price:599, image_url:"https://kated.com/wp-content/uploads/2020/04/TZA9a-Hot-air-Baloon-FLight-Serengeti.jpg", includes:"", likes:614)
e13= Experience.create(name: "Sunrise Taj Mahal Trip from Delhi",location:"New Delhi, India", description:"Make a tour to Agra easy and stress-free with round-trip private transportation and a dedicated guide. Make your own schedule for pickup and drop-off at your New Delhi hotel; move at your own pace while exploring the landmarks in Agra. Lunch at a top Agra restaurant and entry fees to sites visited are included in the tour price.", price:130, image_url:"https://d3emaq2p21aram.cloudfront.net/media/cache/report_image_flex/uploads/0_BLOG/2018/6-June/TajMahal/TajMahal-fahramineuse-01.jpg ", includes:"", likes:231)
e14= Experience.create(name: "Golden Circle, Blue Lagoon Including Admission & Kerid Volcanic Crater",location:"Reykjavik, Ice Island", description:"Make the most of your time in Iceland and embark on a jam-packed day of the country’s key attractions with a small group. Start your day bright and early for your drive around the Golden Circle, stopping at Thingvellir, Geysir Hot Spring, Gullfoss, and the Kerid volcanic crater. Then, end your day with a soak in the geothermal waters of the Blue Lagoon.", price:207, image_url:"https://mediaim.expedia.com/localexpert/514906/fff6a29a-f5df-44bd-99ef-4a2f0288a996.jpg ", includes:"", likes:614 )
e15= Experience.create(name: "Luxury Yacht. Private Full or Half Day Catamaran Snorkel, & Beach Experience",location:"Adrenaline enthusiasts looking for an unforgettable experience will love ziplining through the Caribbean rainforest on St. Thomas. Soar through the air on 8 different platforms, reaching speeds of up to 35 miles per hour (56 km/h) as you take in stunning views of the ocean. Your knowledgeable guides will entertain you with stories about the Virgin Islands' culture, flora, and fauna, making this an adventure you won't soon forget. For a truly unique thrill, don't miss the Yo-Yo, the only zipline of its kind in the Caribbean!", price: 145, image_url:"https://media.cntraveler.com/photos/609d3b3eba01da3e65cb6a5c/16:9/w_2560%2Cc_limit/RosewoodLittleDixBay_AerialView.jpg ", includes:"", likes:530)
e16= Experience.create(name: "Tree Limin' Extreme Zipline",location:"St, Thomas, Us Virgin Island", description:"Make the most of your time in Iceland and embark on a jam-packed day of the country’s key attractions with a small group. Start your day bright and early for your drive around the Golden Circle, stopping at Thingvellir, Geysir Hot Spring, Gullfoss, and the Kerid volcanic crater. Then, end your day with a soak in the geothermal waters of the Blue Lagoon.", price:207, image_url:"https://img2.10bestmedia.com/Images/Photos/211734/p-DSC-0181_55_660x440_201404232024.JPG", includes:"", likes:212)
e17= Experience.create(name: "Panoramic Helicopter Flight over Iguassu Falls", location:"Foz Do Iguacu, Brazil", description: "Since 1972 we have performed panoramic flights in the city of Foz do Iguaçu. A unique experience lived by over three million passengers from all corners of the world, who were privileged with an exclusive view of the Iguazu Falls, one of the seven wonders of the world, and also with the view of other sights of the region.
    All our flights and operations comply with aviation, environmental, and especially the strictest safety standards. Our company is aware of its role in relation to the environment, so we spread and practice this idea.
    Since 2004 we have adhered to the Internal Environmental Management Program, achieving in 2006 the ISO 14000 certificate. Thus Helisul Táxi Aéreo became the first Brazilian civil aviation company to have ISO 14000.
    ", price:155, image_url: "https://et-website.s3.amazonaws.com/uploads/2018/08/Enchanting-Travels-South-America-Tours-Aerial-View-of-Iguazu-Falls.jpg ", includes:"", likes:69)
e18= Experience.create(name: "Monuments of the Ottoman Empire", location:"Istanbul, Turkey", description: "Witness the classic sites of heritage and history that abound in Istanbul on your full-day tour. Visit architectural masterpieces, marvel at awe-inspiring, Byzantine-era tileworks, and see the imperial treasures of Ottoman sultans. Along the way, experience the customs of at a bustling bazaar.
Your tour starts with a brief stop at the Hippodrome, once the sporting and social center of the Roman capital of Constantinople, and still home to a few remaining obelisks. Continue on to the Byzantine basilica, Hagia Sophia, where 30 million gold tesserae (tiny mosaic tiles) create stunning mosaics and and the great calligraphic panes line the interior.
Put your haggling skills to the test and find a bargain at the Grand Bazaar, or simply observe the trade of diamonds, perfume, food, and rugs, before moving on to the Sultan Ahmet-inspired masterpiece—The Blue Mosque. Admire the mosque's finely decorated Ottoman tiles and stained-glass windows and learn about the lives of pasty royalty at the solemn Tomb of Sultan Ahmet.
After lunch, meander through the regal rooms of the Topkapi Palace, the residence of the Ottoman sultans from the 15th to the 19th centuries. See the imperial treasury and its collection of Chinese porcelain, costumes, and weaponry, and complete your day with a visit to the Tombs of Ottoman Sultans within the graveyard at Hagia Sophia. Each of the five tombs actually houses the sultan as well as his family. Each architecture has different decorations, including works by Mimar Sinan. The ceramic panels are the most beautiful examples of the 16th century with purple, red, green and blue flower figures.", price:87, image_url: "https://quiltripping.com/wp-content/uploads/2018/05/DSC_0922-1200x795.jpg", includes:"", likes:420)
e19= Experience.create(name: "Machu Picchu", location:"Machu Pichu, Peru", description: "The UNESCO–listed site of Machu Picchu ranks among the most important Incan treasures in South America, with a hidden history dating back thousands of years. On this tour, visit sites including the Sun Temple and the Room of the Three Windows with your guide, and delve into a civilization lost in time. When your guided visit ends, stay at Machu Picchu to explore on your own and soak up the mountain scenery.", price:18, image_url: " https://www.peru.travel/Contenido/Atractivo/Imagen/en/172/1.1/Principal/machu-picchu.jpg", includes:"", likes: 219)
e20= Experience.create(name: "Cradle of Humankind Johannesburg, South Africa", location:"Johannesburg, South Africa", description: "The Cradle of Humankind was declared a World Heritage Site in 1999 because of the area’s exceptional contribution to our understanding of the history of humanity, over 3-million years. All together, there are 15 major fossil sites in the Cradle of Humankind, of which Sterkfontein Caves is the most famous.
The fossils “Mrs Ples” and “Little Foot” were both discovered at the Sterkfontein Caves, as well as thousands more fossils of hominids, which are human ancestors, as well those of plants and animals.
More hominid fossils have been found in the Cradle of Humankind than anywhere else on Earth.
During this tour you will have access to the exhibits and get the full pictures of remarkable fossil findings.
", price:96, image_url: "https://www.andbeyond.com/wp-content/uploads/sites/5/Sterkfontein-Caves-Maropeng.jpg ", includes:"", likes:129)
puts "Experiences seeded!"

puts "Seeding bookings..."

b1= Booking.create(user_id: u1.id, experience_id: e3.id, datetime:'06/30/2022 18:30', people_count: 2 , total_price: 950)
b2= Booking.create(user_id: u2.id, experience_id: e11.id, datetime:'06/30/2022 18:30', people_count: 2, total_price: 3000)
b3= Booking.create(user_id: u3.id, experience_id: e1.id, datetime:'06/30/2022 18:30', people_count: 2, total_price: 1384)
b4= Booking.create(user_id: u1.id, experience_id: e6.id, datetime:'06/30/2022 18:30', people_count: 4, total_price: 608)
b5= Booking.create(user_id: u2.id, experience_id: e9.id, datetime:'06/30/2022 18:30', people_count: 4, total_price: 1476)
b6= Booking.create(user_id: u3.id, experience_id: e17.id, datetime:'06/30/2022 18:30', people_count: 4, total_price: 620)

puts "Bookings seeded!"